const { faker } = require("@faker-js/faker"); // Require Faker
const { Article, User, Comment } = require("../models"); // Require models

faker.locale = "es";

module.exports = async () => {
  const articles = []; // Create resources as empty arrays
  const users = [];
  const comments = [];

  for (let i = 0; i < 100; i++) {
    const randomId = () => {
      let result = Math.floor(Math.random() * 99) + 1;
      return result;
    };

    articles.push({
      // Push content generated by faker to arrays
      title: faker.lorem.sentence(5),
      content: faker.lorem.paragraphs(),
      image: faker.datatype.number({ min: 1, max: 3 }) + ".png", // Image files randomly assigned to articles
      userId: randomId(),
    });

    // In the first iteration, the user created is "Anónimo desconocido", this will help when a deleted user has comments or articles.
    if (i !== 0) {
      users.push({
        firstname: await faker.name.firstName(),
        lastname: await faker.name.lastName(),
        email: faker.internet.email(),
      });
    } else {
      users.push({
        firstname: "Anónimo",
        lastname: "desconocido",
        email: "-----",
      });
    }
    comments.push({
      content: faker.lorem.paragraph(),
      userId: randomId(),
      articleId: randomId(),
    });
  }

  await User.bulkCreate(users); // Sequelize method to push new arrays to DB
  await Article.bulkCreate(articles);
  await Comment.bulkCreate(comments);
  console.log("[Database] Se corrió el seeder de Articles."); // Console log to know that the arrays were pushed successfully
};
